[package]
name = "setops"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/UNSW-database/simd_set_operations"
features = ["simd", "portable_simd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
