[package]
name = "setops"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/UNSW-database/simd_set_operations"
features = ["simd", "portable_simd"]

[profile.bench]
lto = "fat"
# Let benchmark use all SIMD features of current CPU.
target-cpu = "native"

[dependencies]

[dev-dependencies]
quickcheck = "1"
criterion = "0.3"
rand = "0.8.5"

[[bench]]
name = "bench_intersect"
harness = false
