[workspace]
members = ["setops", "benchmarks"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/UNSW-database/simd_set_operations"

[profile.release]
lto = true
panic = "abort"
