
[algorithm_sets]
scalar_2set = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
]
vector_2set = [
    "branchless_merge",
    "shuffling_sse", "shuffling_avx2",
    "broadcast_sse", "broadcast_avx2",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "croaring", "roaringrs",
    "fesia8_sse_0.01", "fesia8_avx2_0.01",
]
bsr_2set = [
    "branchless_merge", "branchless_merge_bsr",
    "shuffling_sse", "shuffling_avx2",
    "shuffling_sse_bsr", "shuffling_avx2_bsr",
    "broadcast_sse", "broadcast_avx2",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter", "qfilter_bsr",
    "croaring", "roaringrs",
    "fesia8_sse_0.01", "fesia8_avx2_0.01",
]
skewed_2set = [
    "branchless_merge",
    "galloping", "galloping_sse", "galloping_avx2",
    "baezayates",
    "shuffling_sse", "shuffling_avx2",
    "croaring", "roaringrs",
    "fesia8_sse_0.01", "fesia8_avx2_0.01",
]
skewed_bsr_2set = [
    "branchless_merge", "branchless_merge_bsr",
    "galloping", "galloping_sse", "galloping_avx2",
    "galloping_bsr", "galloping_sse_bsr", "galloping_avx2_bsr",
    "baezayates",
    "shuffling_sse", "shuffling_avx2",
    "shuffling_sse_bsr", "shuffling_avx2_bsr",
    "croaring", "roaringrs",
    "fesia8_sse_0.01", "fesia8_avx2_0.01",
]
fesia_bench = [
    "branchless_merge",# "shuffling_sse",
    "fesia8_sse_0.01",  "fesia16_sse_0.01", "fesia32_sse_0.01",
    "fesia8_sse_0.05",  "fesia16_sse_0.05", "fesia32_sse_0.05",
]
fesia_compare_block_bits = [
    "fesia8_sse_0.01",    "fesia16_sse_0.01",    "fesia32_sse_0.01",
    "fesia8_avx2_0.01",   "fesia16_avx2_0.01",   "fesia32_avx2_0.01",
#   "fesia8_avx512", "fesia16_avx512", "fesia32_avx512",
]
fesia_compare_hash_scale = [
    "fesia8_sse_0.005", "fesia8_sse_0.01", "fesia8_sse_0.05",
    "fesia8_avx2_0.005","fesia8_avx2_0.01", "fesia8_avx2_0.05",
]
fesia_hash_compare_block_bits = [
    "fesia_hash8_sse_2", "fesia_hash16_sse_2", "fesia_hash32_sse_2",
]
fesia_hash_compare_hash_scale = [
    "fesia_hash8_sse_0.005", "fesia_hash8_sse_0.01", "fesia_hash8_sse_0.05",
]
scalar_kset = [
    # "adaptive",
    "small_adaptive",
    "branchless_merge",
    "galloping",
    "baezayates",
]
vector_kset = [
    # "adaptive",
    "small_adaptive",
    "branchless_merge",
    "galloping", "galloping_sse", "galloping_avx2",
    "baezayates",

    "shuffling_sse", "shuffling_avx2",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "broadcast_sse", "broadcast_avx2",
    "croaring", "roaringrs",
]

## EXPERIMENTS ##

[[experiment]]
name = "scalar_2set_vary_selectivity"
title = "Scalar 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithm_set = "scalar_2set"
relative_to = "naive_merge"

[[experiment]]
name = "vector_2set_vary_selectivity"
title = "Vector 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithm_set = "vector_2set"
relative_to = "branchless_merge"

[[experiment]]
name = "2set_vary_density"
title = "Vector 2-set varying selectivity"
dataset = "2set_vary_density"
algorithm_set = "bsr_2set"
relative_to = "branchless_merge"

[[experiment]]
name = "2set_vary_skew"
title = "2-set varying skew"
dataset = "2set_vary_skew"
algorithm_set = "skewed_2set"

[[experiment]]
name = "2set_vary_density_skewed"
title = "Skewed 2-set varying density (skew 1:256)"
dataset = "2set_vary_density_skewed"
algorithm_set = "skewed_bsr_2set"
relative_to = "branchless_merge"

[[experiment]]
name = "fesia_bench"
title = "2-set varying selectivity"
dataset = "fesia_vary_sel"
algorithm_set = "fesia_bench"
relative_to = "branchless_merge"

[[experiment]]
name = "fesia_2set_vary_selectivity_block"
title = "FESIA 2-set varying selectivity compare block size"
dataset = "2set_vary_selectivity"
algorithm_set = "fesia_compare_block_bits"
relative_to = "fesia16_sse_0.01"

[[experiment]]
name = "fesia_2set_vary_density_block"
title = "FESIA 2-set varying density"
dataset = "2set_vary_density"
algorithm_set = "fesia_compare_block_bits"
relative_to = "fesia16_sse_0.01"

[[experiment]]
name = "fesia_2set_vary_selectivity_hash"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "fesia_hash_scale_vary_sel"
algorithm_set = "fesia_compare_hash_scale"
relative_to = "fesia8_sse_0.05"

[[experiment]]
name = "fesia_2set_vary_density_hash"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "fesia_hash_scale_vary_den"
algorithm_set = "fesia_compare_hash_scale"
relative_to = "fesia8_sse_0.05"

[[experiment]]
name = "fesia_hash_2set_block_sizes"
title = "FESIA 2-set varying selectivity compare block size"
dataset = "2set_vary_selectivity"
algorithm_set = "fesia_hash_compare_block_bits"

[[experiment]]
name = "fesia_hash_2set_hash_scales"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "2set_vary_selectivity"
algorithm_set = "fesia_hash_compare_hash_scale"

[[experiment]]
name = "kset_same_size_scalar"
title = "k-set same size scalar"
dataset = "kset_same_size"
algorithm_set = "scalar_kset"

[[experiment]]
name = "kset_same_size_vector"
title = "k-set same size vector"
dataset = "kset_same_size"
algorithm_set = "vector_kset"

[[experiment]]
name = "4set_vary_skew_small"
title = "k-set same size vector"
dataset = "kset_same_size"
algorithm_set = "vector_kset"

[[experiment]]
name = "webdocs_scalar"
title = "k-set same size scalar"
dataset = "webdocs"
algorithm_set = "scalar_kset"
relative_to = "branchless_merge"

[[experiment]]
name = "webdocs_vector"
title = "k-set same size scalar"
dataset = "webdocs"
algorithm_set = "vector_kset"
relative_to = "branchless_merge"

## DATASETS ##
# density     -- linear 0-1000 === 0-100%
# selectivity -- linear 0-1000 === 0-100%
# skewness_factor f -- exponential (k^f) for set k
# max_len         n -- exponential (2^n)

[[dataset]]
name = "2set_vary_selectivity"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 1000
step = 100
skewness_factor = 0 # 1:2^0 === 1:1
density = 1         # 0.1%
max_len = 20        # 2^20 ~ 1M

[[dataset]]
name = "2set_vary_density"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
skewness_factor = 0
selectivity = 30
max_len = 20

[[dataset]]
name = "2set_vary_skew"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 13000
step = 1000
density = 1
selectivity = 10
max_len = 23

[[dataset]]
name = "2set_vary_density_skewed"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
skewness_factor = 8
selectivity = 30
max_len = 20

[[dataset]]
name = "kset_same_size"
type = "synthetic"
gen_count = 10
vary = "set_count"
set_count = 2
to = 8
step = 1
density = 1
selectivity = 10
skewness_factor = 0
max_len = 20

[[dataset]]
name = "kset_skew_1"
type = "synthetic"
gen_count = 10
vary = "set_count"
set_count = 2
to = 8
step = 1
density = 1
selectivity = 10
skewness_factor = 1000
max_len = 23

[[dataset]]
name = "4set_vary_skew_small"
type = "synthetic"
set_count = 4
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 1000
step = 100
density = 1
selectivity = 10
max_len = 20

[[dataset]]
name = "4set_vary_skew_large"
type = "synthetic"
set_count = 4
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 8000
step = 500
density = 1
selectivity = 10
max_len = 23

[[dataset]]
name = "fesia_vary_sel"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 500
step = 100
skewness_factor = 0
density = 1
max_len = 20

[[dataset]]
name = "fesia_hash_scale_vary_sel"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 100
step = 20
skewness_factor = 0
density = 1
max_len = 23

[[dataset]]
name = "fesia_hash_scale_vary_den"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
selectivity = 0
skewness_factor = 0
max_len = 23

[[dataset]]
name = "webdocs"
type = "real"
gen_count = 1024
set_count_start = 2
set_count_end = 8
