
[algorithm_sets]
scalar_kset = [
    # "adaptive",
    "small_adaptive",
    "branchless_merge",
    "galloping",
    "binary_search",
    "baezayates",
]
vector_kset = [
    # "adaptive",
    "small_adaptive",
    "branchless_merge",
    "galloping", "galloping_sse", "galloping_avx2", "galloping_avx512",
    "binary_search",
    "baezayates",

    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "vp2intersect_emulation", "conflict_intersect",
    "broadcast_sse", "broadcast_avx2", "broadcast_avx512",
    "vp2intersect_emulation", "conflict_intersect",
    "croaring", "roaringrs",
    "fesia16_sse_10.0", "fesia16_avx2_10.0", "fesia32_avx512_10.0",
]

## EXPERIMENTS ##

# Vary selectivity
[[experiment]]
name = "scalar_2set_vary_selectivity"
title = "Scalar 2-set varying selectivity"
dataset = "2set_vary_selectivity"
relative_to = "naive_merge"
algorithms = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
]

[[experiment]]
name = "array_2set_vary_selectivity"
title = "2-set array-based algorithms varying selectivity"
dataset = "2set_vary_selectivity"
relative_to = "branchless_merge"
algorithms = [
    "branchless_merge",
    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "broadcast_sse", "broadcast_avx2", "broadcast_avx512",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "vp2intersect_emulation", "conflict_intersect",
]

[[experiment]]
name = "custom_2set_vary_selectivity"
title = "2-set array-based algorithms varying selectivity"
dataset = "2set_vary_selectivity"
relative_to = "branchless_merge"
algorithms = [
    "branchless_merge",
    "croaring", "roaringrs",
    "fesia16_sse_10.0", "fesia16_avx2_10.0", "fesia16_avx512_10.0",
]

[[experiment]]
name = "vector_2set_vary_selectivity"
title = "Vector 2-set varying selectivity"
dataset = "2set_vary_selectivity"
relative_to = "branchless_merge"
algorithms = [
    "branchless_merge",
    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "broadcast_sse", "broadcast_avx2", "broadcast_avx512", # later: hide
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "vp2intersect_emulation", "conflict_intersect",
    "croaring", "roaringrs",
    "fesia16_sse_10.0", "fesia16_avx2_10.0", "fesia32_avx512_10.0",
]

# Vary density
[[experiment]]
name = "bsr_2set_vary_density"
title = "2-set algorithms varying density -- array vs BSR"
dataset = "2set_vary_density"
algorithms = [
    "branchless_merge", "branchless_merge_bsr",
    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "shuffling_sse_bsr", "shuffling_avx2_bsr",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter", "qfilter_bsr",
]

[[experiment]]
name = "2set_vary_density"
title = "2-set algorithms varying density"
dataset = "2set_vary_density"
algorithms = [
    "branchless_merge", "branchless_merge_bsr",
    # "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "shuffling_sse_bsr", "shuffling_avx2_bsr",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter", "qfilter_bsr",
    "vp2intersect_emulation", "conflict_intersect",
    "croaring", "roaringrs",
    "fesia16_sse_10.0", "fesia16_avx2_10.0", "fesia32_avx512_10.0",
]

# Skewed intersection
[[experiment]]
name = "array_2set_vary_skew"
title = "2-set varying skew"
dataset = "2set_vary_skew"
algorithms = [
    "branchless_merge",
    "galloping", "galloping_sse", "galloping_avx2", "galloping_avx512",
    "binary_search",
    "baezayates",
    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "bmiss_sse", "bmiss_sse_sttni", "qfilter",
    "vp2intersect_emulation", "conflict_intersect",
]

[[experiment]]
name = "2set_vary_skew"
title = "2-set varying skew"
dataset = "2set_vary_skew"
algorithms = [
    "branchless_merge",
    "galloping", "galloping_sse", "galloping_avx2", "galloping_avx512",
    "binary_search",
    "baezayates",
    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "bmiss_sse", "bmiss_sse_sttni", "qfilter",
    "croaring", "roaringrs",
    "vp2intersect_emulation", "conflict_intersect",
    "fesia16_sse_10.0", "fesia16_avx2_10.0", "fesia32_avx512_10.0",
    "fesia_hash8_sse_10.0", "fesia_hash8_avx2_10.0", "fesia_hash8_avx512_10.0",
]

[[experiment]]
name = "2set_vary_density_skewed"
title = "Skewed 2-set varying density (skew 1:256)"
dataset = "2set_vary_density_skewed"
relative_to = "branchless_merge"
algorithms = [
    "branchless_merge", "branchless_merge_bsr",
    "galloping", "galloping_sse", "galloping_avx2", "galloping_avx512",
    "binary_search",
    "galloping_bsr", "galloping_sse_bsr", "galloping_avx2_bsr", "galloping_avx512_bsr",
    "baezayates",
    # "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "shuffling_sse_bsr", "shuffling_avx2_bsr", "shuffling_avx512_bsr",
    "croaring", "roaringrs",
    "vp2intersect_emulation", "conflict_intersect",
    "fesia16_sse_10.0", "fesia8_avx16_10.0", "fesia32_avx512_10.0",
    "fesia_hash8_sse_10.0", "fesia_hash8_avx2_10.0", "fesia_hash8_avx512_10.0",
]

# FESIA
[[experiment]]
name = "fesia_bench"
title = "2-set varying selectivity"
dataset = "fesia_vary_sel"
relative_to = "branchless_merge"
algorithms = [
    "branchless_merge",
    "shuffling_sse", "shuffling_avx2", "shuffling_avx512",
    "vp2intersect_emulation",
    "croaring",
    "fesia16_sse_10.0",
    "fesia32_sse_10.0",
    "fesia16_avx2_10.0",
    "fesia32_avx2_10.0",
    "fesia16_avx512_10.0",
    "fesia32_avx512_10.0",
]

[[experiment]]
name = "fesia_2set_vary_selectivity_block"
title = "FESIA 2-set varying selectivity compare block size"
dataset = "2set_vary_selectivity"
relative_to = "fesia8_sse_10.0"
algorithms = [
    "fesia8_sse_10.0",  "fesia16_sse_10.0",  "fesia32_sse_10.0",
    "fesia8_avx2_10.0", "fesia16_avx2_10.0", "fesia32_avx2_10.0",
    "fesia8_avx512_10.0",    "fesia16_avx512_10.0",    "fesia32_avx512_10.0",
]

[[experiment]]
name = "fesia_2set_vary_selectivity_hash"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "2set_vary_selectivity"
relative_to = "fesia16_sse_1.0"
algorithms = [
    "fesia16_sse_1.0", "fesia16_sse_5.0", "fesia16_sse_10.0", "fesia16_sse_20.0",
    "fesia16_avx2_1.0","fesia16_avx2_5.0", "fesia16_avx2_10.0", "fesia16_avx2_20.0",
    "fesia32_avx512_1.0","fesia32_avx512_5.0", "fesia32_avx512_10.0", "fesia32_avx512_20.0",
]

[[experiment]]
name = "fesia_hash_2set_block_sizes"
title = "FESIA 2-set varying selectivity compare block size"
dataset = "2set_vary_selectivity"
algorithms = [
    "fesia_hash8_sse_10.0", "fesia_hash16_sse_10.0", "fesia_hash32_sse_10.0",
    "fesia_hash8_avx2_10.0", "fesia_hash16_avx2_10.0", "fesia_hash32_avx2_10.0",
    "fesia_hash8_avx512_10.0", "fesia_hash16_avx512_10.0", "fesia_hash32_avx512_10.0",
]

[[experiment]]
name = "fesia_hash_2set_hash_scales"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "2set_vary_selectivity"
algorithms = [
    "fesia_hash16_sse_1.0", "fesia_hash16_sse_5.0", "fesia_hash16_sse_10.0", "fesia_hash16_sse_20.0",
    "fesia_hash16_avx2_1.0", "fesia_hash16_avx2_5.0", "fesia_hash16_avx2_10.0", "fesia_hash16_avx2_20.0",
    "fesia_hash16_avx512_1.0", "fesia_hash16_avx512_5.0", "fesia_hash16_avx512_10.0", "fesia_hash16_avx512_20.0",
]

# K-set intersection
[[experiment]]
name = "kset_same_size_scalar"
title = "k-set same size scalar"
dataset = "kset_same_size"
algorithm_set = "scalar_kset"

[[experiment]]
name = "kset_same_size_vector"
title = "k-set same size vector"
dataset = "kset_same_size"
algorithm_set = "vector_kset"

[[experiment]]
name = "4set_vary_skew_small"
title = "k-set same size vector"
dataset = "4set_vary_skew_small"
algorithm_set = "vector_kset"

# Real datasets
[[experiment]]
name = "webdocs_scalar"
title = "WebDocs scalar"
dataset = "webdocs"
algorithm_set = "scalar_kset"
relative_to = "branchless_merge"

[[experiment]]
name = "webdocs_compare_small_adaptive"
title = "WebDocs Small Adaptive Comparison"
dataset = "webdocs"
algorithms = [
    "small_adaptive",
    "small_adaptive_sorted",
]

[[experiment]]
name = "webdocs_vector"
title = "WebDocs vector"
dataset = "webdocs"
algorithm_set = "vector_kset"
relative_to = "branchless_merge"

[[experiment]]
name = "twitter_vector"
title = "Twitter graph dataset -- vector algorithms"
dataset = "twitter"
algorithm_set = "vector_kset"
relative_to = "branchless_merge"

[[experiment]]
name = "as_skitter_vector"
title = "Autonomous System graph dataset -- vector algorithms"
dataset = "as-skitter"
algorithm_set = "vector_kset"
relative_to = "branchless_merge"

## DATASETS ##
# density     -- linear 0-1000 === 0-100%
# selectivity -- linear 0-1000 === 0-100%
# skewness_factor f -- exponential (k^f) for set k
# max_len         n -- exponential (2^n)

[[dataset]]
name = "2set_vary_selectivity"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 1000
step = 100
skewness_factor = 0 # 1:2^0 === 1:1
density = 1         # 0.1%
max_len = 20        # 2^20 ~ 1M

[[dataset]]
name = "2set_vary_density"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
skewness_factor = 0
selectivity = 30
max_len = 20

[[dataset]]
name = "2set_vary_skew"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 13000
step = 1000
density = 1
selectivity = 10
max_len = 23

[[dataset]]
name = "2set_vary_density_skewed"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
skewness_factor = 8
selectivity = 30
max_len = 20

[[dataset]]
name = "kset_same_size"
type = "synthetic"
gen_count = 10
vary = "set_count"
set_count = 2
to = 8
step = 1
density = 1
selectivity = 10
skewness_factor = 0
max_len = 20

[[dataset]]
name = "kset_skew_1"
type = "synthetic"
gen_count = 10
vary = "set_count"
set_count = 2
to = 8
step = 1
density = 1
selectivity = 10
skewness_factor = 1000
max_len = 23

[[dataset]]
name = "4set_vary_skew_small"
type = "synthetic"
set_count = 4
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 1000
step = 100
density = 1
selectivity = 10
max_len = 20

[[dataset]]
name = "4set_vary_skew_large"
type = "synthetic"
set_count = 4
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 8000
step = 500
density = 1
selectivity = 10
max_len = 23

[[dataset]]
name = "fesia_vary_sel"
type = "synthetic"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 500
step = 100
skewness_factor = 0
density = 1
max_len = 20

[[dataset]]
name = "webdocs"
type = "real"
source = "webdocs"
gen_count = 1024
set_count_start = 2
set_count_end = 8

[[dataset]]
name = "twitter"
type = "real"
source = "twitter"
gen_count = 1024
set_count_start = 2
set_count_end = 8

[[dataset]]
name = "as-skitter"
type = "real"
source = "as-skitter"
gen_count = 1024
set_count_start = 2
set_count_end = 8
