## Parameters ##
# density     -- linear 0-1000 === 0-100%
# selectivity -- linear 0-1000 === 0-100%
# skew        -- exponential (2^(n-1))
# size        -- exponential (2^n)

[[experiment]]
name = "scalar_2set_vary_selectivity"
dataset = "2set_vary_selectivity"
algorithms = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
    "galloping", "baezayates",
]

[[dataset]]
name = "2set_vary_selectivity"
type = "2set"
vary = "selectivity"
selectivity = 0
to = 1000
step = 100
skew = 1
density = 1
size = 20
count = 10

[[dataset]]
name = "2set_vary_density"
type = "2set"
vary = "density"
density = 0
to = 1000
step = 100
skew = 1
selectivity = 300
size = 20
count = 8
