## Parameters ##
# density     -- linear 0-1000 === 0-100%
# selectivity -- linear 0-1000 === 0-100%
# skew        -- exponential (2^(n-1))
# size        -- exponential (2^n)

[[experiment]]
name = "scalar_2set_vary_selectivity"
title = "Scalar 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithms = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
]

[[experiment]]
name = "vector_2set_vary_selectivity"
title = "Vector 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithms = [
    "branchless_merge",
    "shuffling_sse",
    "broadcast_sse",
    "bmiss_sse",
    "bmiss_sse_sttni",
    "qfilter",
    "shuffling_avx2",
    "broadcast_avx2",
]

[[experiment]]
name = "fesia_2set_vary_selectivity_block"
title = "FESIA 2-set varying selectivity compare block size"
dataset = "2set_vary_selectivity"
algorithms = [
    "fesia8_sse_2",    "fesia16_sse_2",    "fesia32_sse_2",
    "fesia8_avx2_2",   "fesia16_avx2_2",   "fesia32_avx2_2",
#   "fesia8_avx512", "fesia16_avx512", "fesia32_avx512",
]

[[experiment]]
name = "fesia_2set_vary_density"
title = "FESIA 2-set varying density"
dataset = "2set_vary_selectivity"
algorithms = [
    "fesia8_sse",    "fesia16_sse",    "fesia32_sse",
    "fesia8_avx2",   "fesia16_avx2",   "fesia32_avx2",
#   "fesia8_avx512", "fesia16_avx512", "fesia32_avx512",
]

[[experiment]]
name = "fesia_2set_vary_selectivity_hash"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "fesia_hash_size_vary_sel"
algorithms = [
    "fesia32_sse_0.0001", "fesia32_sse_0.001", "fesia32_sse_0.01",    "fesia32_sse_0.1",#    "fesia32_sse_0.5",    "fesia32_sse_1.0", # "fesia32_sse_2.0",
    "fesia32_avx2_0.0001","fesia32_avx2_0.001","fesia32_avx2_0.01",   "fesia32_avx2_0.1",#   "fesia32_avx2_0.5",   "fesia32_avx2_1.0",# "fesia32_avx2_2.0",
]

[[experiment]]
name = "2set_vary_skew"
title = "2-set varying skew"
dataset = "2set_vary_skew_s10"
algorithms = [
    "branchless_merge",
    "galloping",
    "galloping_sse",
    "galloping_avx2",
    "baezayates",
    "baezayates_opt",
    "shuffling_sse",
    "shuffling_avx2",
]

[[dataset]]
name = "2set_vary_selectivity"
type = "2set"
vary = "selectivity"
selectivity = 0
to = 1000
step = 100
skew = 1
density = 1
size = 20
count = 10

[[dataset]]
name = "2set_vary_density"
type = "2set"
vary = "density"
density = 0
to = 1000
step = 100
skew = 1
selectivity = 300
size = 20
count = 10

[[dataset]]
name = "2set_vary_skew_s10"
type = "2set"
vary = "skew"
skew = 1
to = 17
step = 1
density = 1
selectivity = 10
size = 10
count = 10

[[dataset]]
name = "fesia_hash_size_vary_sel"
type = "2set"
vary = "selectivity"
selectivity = 0
to = 100
step = 20
skew = 1
density = 1
size = 23
count = 10
