# Multiple experiments may operate on a single dataset.

# Processing considerations:
# - Reuse data from other experiments if algorithms overlap?
#   later - doesn't work with critereon graphs.
# - Performance in terms of other algorithms?
# - Group by dataset, experiment is only used for later processing.

[[group]]
name = "Scalar 2-set with Varying Selectivity"
type = "2set"
algorithms = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
    "galloping", "baezayates",
]


[[dataset]]
type = "2set"
vary = "selectivity"
selectivity = 1
to = 1000
skew = 1
density = 1
size = 20
count = 32

[[dataset]]
type = "2set"
vary = "density"
density = 1
to = 1000
skew = 1
selectivity = 10
size = 20
count = 32
