## Parameters ##
# density     -- linear 0-1000 === 0-100%
# selectivity -- linear 0-1000 === 0-100%
# skewness_factor -- exponential (k^f)
# size        -- exponential (2^n)

[[experiment]]
name = "scalar_2set_vary_selectivity"
title = "Scalar 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithms = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
]

[[experiment]]
name = "vector_2set_vary_selectivity"
title = "Vector 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithms = [
    "branchless_merge",
    "shuffling_sse", "shuffling_avx2",
    "broadcast_sse", "broadcast_avx2",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "croaring",
    "fesia8_sse_0.01", "fesia8_avx2_0.01",
]

[[experiment]]
name = "vector_2set_vary_density"
title = "Vector 2-set varying selectivity"
dataset = "2set_vary_selectivity"
algorithms = [
    "branchless_merge", "branchless_merge_bsr",
    "shuffling_sse", "shuffling_sse_bsr",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter", "qfilter_bsr",
    "shuffling_avx2", "shuffling_avx2_bsr",
    "croaring",
    "fesia8_sse_0.01", "fesia8_avx2_0.01",
]

[[experiment]]
name = "fesia_2set_vary_selectivity_block"
title = "FESIA 2-set varying selectivity compare block size"
dataset = "2set_vary_selectivity"
algorithms = [
    "fesia8_sse_2",    "fesia16_sse_2",    "fesia32_sse_2",
    "fesia8_avx2_2",   "fesia16_avx2_2",   "fesia32_avx2_2",
#   "fesia8_avx512", "fesia16_avx512", "fesia32_avx512",
]

[[experiment]]
name = "fesia_2set_vary_density_block"
title = "FESIA 2-set varying density"
dataset = "2set_vary_density"
algorithms = [
    "fesia8_sse_2",    "fesia16_sse_2",    "fesia32_sse_2",
    "fesia8_avx2_2",   "fesia16_avx2_2",   "fesia32_avx2_2",
#   "fesia8_avx512", "fesia16_avx512", "fesia32_avx512",
]

[[experiment]]
name = "fesia_2set_vary_selectivity_hash"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "fesia_hash_size_vary_sel"
algorithms = [
    "fesia8_sse_0.005", "fesia8_sse_0.01", "fesia8_sse_0.05",
    "fesia8_avx2_0.005","fesia8_avx2_0.01", "fesia8_avx2_0.05",
]

[[experiment]]
name = "fesia_2set_vary_density_hash"
title = "FESIA 2-set varying selectivity compare hash size"
dataset = "fesia_hash_size_vary_den"
algorithms = [
    "fesia8_sse_0.0001", "fesia8_sse_0.001", "fesia8_sse_0.01",    "fesia8_sse_0.1",#    "fesia8_sse_0.5",    "fesia8_sse_1.0", # "fesia8_sse_2.0",
    "fesia8_avx2_0.0001","fesia8_avx2_0.001","fesia8_avx2_0.01",   "fesia8_avx2_0.1",#   "fesia8_avx2_0.5",   "fesia8_avx2_1.0",# "fesia8_avx2_2.0",
]

[[experiment]]
name = "2set_vary_skew"
title = "2-set varying skew"
dataset = "2set_vary_skew"
algorithms = [
    "branchless_merge",
    "galloping", "galloping_sse", "galloping_avx2",
    "baezayates", "baezayates_opt",
    "shuffling_sse", "shuffling_avx2",
    "croaring",
]

[[experiment]]
name = "kset_same_size_scalar"
title = "k-set same size scalar"
dataset = "kset_same_size"
algorithms = [
    "adaptive", "small_adaptive",
    "branchless_merge",
    "galloping",
    "baezayates", "baezayates_opt",
]

[[experiment]]
name = "kset_same_size_vector"
title = "k-set same size vector"
dataset = "kset_same_size"
algorithms = [
    "adaptive", "small_adaptive",
    "branchless_merge",
    "galloping",
    "baezayates", "baezayates_opt",

    "shuffling_sse", "shuffling_avx2",
    "bmiss_sse", "bmiss_sse_sttni",
    "qfilter",
    "broadcast_sse", "broadcast_avx2",
    "croaring",
]

[[dataset]]
name = "2set_vary_selectivity"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 1000
step = 100
skewness_factor = 0
density = 1
max_len = 20

[[dataset]]
name = "2set_vary_density"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
skewness_factor = 0
selectivity = 30
max_len = 20

[[dataset]]
name = "2set_vary_skew"
set_count = 2
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 13000
step = 1000
density = 1
selectivity = 10
max_len = 23

[[dataset]]
name = "kset_same_size"
gen_count = 10
vary = "set_count"
set_count = 2
to = 8
step = 1
density = 1
selectivity = 10
skewness_factor = 0
max_len = 20

[[dataset]]
name = "kset_skew_1"
gen_count = 10
vary = "set_count"
set_count = 2
to = 8
step = 1
density = 1
selectivity = 10
skewness_factor = 1000
max_len = 23

[[dataset]]
name = "4set_vary_skew_small"
set_count = 4
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 1000
step = 100
density = 1
selectivity = 10
max_len = 20

[[dataset]]
name = "4set_vary_skew_large"
set_count = 4
gen_count = 10
vary = "skew"
skewness_factor = 0
to = 8000
step = 500
density = 1
selectivity = 10
max_len = 23

[[dataset]]
name = "fesia_hash_size_vary_sel"
set_count = 2
gen_count = 10
vary = "selectivity"
selectivity = 0
to = 100
step = 20
skewness_factor = 0
density = 1
max_len = 23

[[dataset]]
name = "fesia_hash_size_vary_den"
set_count = 2
gen_count = 10
vary = "density"
density = 0
to = 1000
step = 100
selectivity = 0
skewness_factor = 0
max_len = 23
