# Multiple experiments may operate on a single dataset.

# Processing considerations:
# - Reuse data from other experiments if algorithms overlap?
#   later - doesn't work with critereon graphs.
# - Performance in terms of other algorithms?
# - Group by dataset, experiment is only used for later processing.

[[experiment]]
name = "Scalar 2-set with Varying Selectivity"
dataset = "2set-vary-selectivity"
algorithms = [
    "naive_merge", "branchless_merge",
    "bmiss_scalar_3x", "bmiss_scalar_4x",
    "galloping", "baezayates",
]

[[dataset]]
name = "2set_vary_selectivity"
type = "2set"
vary = "selectivity"
selectivity = 0
to = 1000
step = 100
skew = 1
density = 1
size = 16
count = 8

[[dataset]]
name = "2set_vary_density"
type = "2set"
vary = "density"
density = 0
to = 1000
step = 100
skew = 1
selectivity = 300
size = 16
count = 8

# density -- linear
# selectivity -- linear
# skew -- exponential (2^n)
# size -- exponential (2^n)
