[dataset.u32_4mib]
# 4 bytes per entry, 2^20 entries in longest, 8 trials ~= 48 MiB per configuration
datatype = "U32"
max_length = 0x10_0000
trials = 8
# 220 configurations -> ~10.3 GiB total
selectivity = { from = 0.0, to = 1.0, steps = 11, mode = "linear" }
skew = { from = 0.0001, to = 1.0, step = 10.0, mode = "log" }
density = { from = 0.0005, to = 0.5, step = 10.0, mode = "log" }

[dataset.u64_8mib]
# 8 bytes per entry, 2^20 entries in longest, 8 trials ~= 96 MiB per configuration
datatype = "U64"
max_length = 0x10_0000
trials = 8
# 220 configurations -> ~20.6 GiB total
selectivity = { from = 0.0, to = 1.0, steps = 11, mode = "linear" }
skew = { from = 0.0001, to = 1.0, step = 10.0, mode = "log" }
density = { from = 0.0005, to = 0.5, step = 10.0, mode = "log" }

