[package]
name = "setops"
version.workspace = true
edition.workspace = true
repository.workspace = true


[dependencies]
num = "0.4.0"
smallvec = "1.10.0"
libc = "0.2"

[dev-dependencies]
quickcheck = "1"

[build-dependencies]
cc = "1.0"
bindgen = "0.69.4"

[features]
default = ["simd"]
simd = []

