[package]
name = "setops"
version.workspace = true
edition.workspace = true
repository.workspace = true


[dependencies]
num = "0.4.0"
roaring = { version = "0.10.1", features = ["simd"] }
smallvec = "1.10.0"

[dev-dependencies]
quickcheck = "1"

[features]
default = ["simd"]
simd = []
