[algorithm_set.scalar_linear]
twoset = ["zipper", "zipper_branch_optimized", "zipper_branch_loop_optimized"]
twoset_to_kset = ["svs"]

# [algorithm_set.scalar_search]
# fsearch = ["binary", "exponential", "golomb", "interpolation", "extrapolation_lookback", "extrapolation_lookahead"]
# fsearch_to_twoset = ["basic"]
# twoset_to_kset = ["svs"]
# fsearch_to_kset = ["sequential", "rsequential", "small_adaptive", "max"]

[experiment.example]
count_only = false
cache_warmup = true
algorithm_sets = ["scalar_linear"]

